/* This file is automatically generated. */
#ifndef INT_SIZES_H
#define INT_SIZES_H

#define INT8_T char
#define INT16_T short
#define INT32_T int
#define INT64_T long long
#define PTRINT_T long long

#define INT8_FORMAT "%hhd"
#define INT16_FORMAT "%hd"
#define INT32_FORMAT "%d"
#define INT64_FORMAT "%lld"
#define PTR_FORMAT "%llx"

#define UINT8_T unsigned char
#define UINT16_T unsigned short
#define UINT32_T unsigned int
#define UINT64_T unsigned long long
#define UPTRINT_T unsigned long long

#define UINT8_FORMAT "%hhu"
#define UINT16_FORMAT "%hu"
#define UINT32_FORMAT "%u"
#define UINT64_FORMAT "%llu"
#define UPTR_FORMAT "%llx"
#endif
