#!/usr/bin/env python
# This file is part of MSMAccelerator.
#
# Copyright 2011 Stanford University
#
# MSMAccelerator is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA


import sys
from Emsmbuilder.Trajectory import Trajectory
from argparse import ArgumentParser

parser = ArgumentParser('Monakos: Dump an LH5 trajectory')
parser.add_argument('path_to_lh5' , help='Path to trajectory file')
parser.add_argument('-pdb', help='Dump a PDB. Default=False. If you want to dump \
    a pdb, you need to provide a filename', default=None, type=str)
args = parser.parse_args()
print args

t = Trajectory.LoadTrajectoryFile(args.path_to_lh5)
print 'Length (frames): ', len(t)
print 'Num Atoms: ', t['XYZList'].shape[1]
print 'Num Atom IDs: ', len(t['AtomID'])

if args.pdb is not None:
    t.SaveToPDB(args.pdb)
