#!/usr/bin/env python
import sys
from Emsmbuilder.Trajectory import Trajectory
from argparse import ArgumentParser

parser = ArgumentParser('Monakos: Dump an LH5 trajectory')
parser.add_argument('path_to_lh5' , help='Path to trajectory file')
parser.add_argument('-pdb', help='Dump a PDB. Default=False. If you want to dump \
    a pdb, you need to provide a filename', default=None, type=str)
args = parser.parse_args()
print args

t = Trajectory.LoadTrajectoryFile(args.path_to_lh5)
print 'Length (frames): ', len(t)
print 'Num Atoms: ', t['XYZList'].shape[1]
print 'Num Atom IDs: ', len(t['AtomID'])

if args.pdb is not None:
    t.SaveToPDB(args.pdb)
