#!/usr/bin/env python
import sys, os
#sys.path.append(os.path.join(os.path.split(os.path.abspath(__file__))[0], '..'))
from monakos import Builder, Project
from Emsmbuilder.Trajectory import Trajectory
from argparse import ArgumentParser

raise NotImplementedError('Sorry')

parser = ArgumentParser('Monakos: Force the builder to run a round with the current data')
parser.add_argument('params_fn', help='Monakos Paramters File (yaml)')
args = parser.parse_args()
print args

builder = Builder(Project(args.params_fn))
builder.run_round(checkdata=False)
