#!/usr/bin/env python
# This file is part of MSMAccelerator.
#
# Copyright 2011 Stanford University
#
# MSMAccelerator is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import sys, os
#sys.path.append(os.path.join(os.path.split(os.path.abspath(__file__))[0], '..'))
from monakos import Builder, Project
from Emsmbuilder.Trajectory import Trajectory
from argparse import ArgumentParser

raise NotImplementedError('Sorry')

parser = ArgumentParser('Monakos: Force the builder to run a round with the current data')
parser.add_argument('params_fn', help='Monakos Paramters File (yaml)')
args = parser.parse_args()
print args

builder = Builder(Project(args.params_fn))
builder.run_round(checkdata=False)
