# Generated at Tue Jul 31 17:13:18 PDT 2012 by rmcgibbo@Roberts-MacBook-Pro-2.local

CCTOOLS_INSTALL_DIR=/Users/rmcgibbo/local/cctools
CCTOOLS_PACKAGES= dttools sand allpairs wavefront makeflow ftp_lite s3tools chirp doc apps work_queue

CCTOOLS_CC=@echo COMPILE $@; gcc
CCTOOLS_BASE_CCFLAGS=-D__EXTENSIONS__ -D_LARGEFILE64_SOURCE -D__LARGE64_FILES -Wall -Wno-unknown-pragmas -Wno-deprecated-declarations -fno-exceptions -fPIC -DHAS_LIBREADLINE -DHAS_STRSIGNAL -DHAS_PREAD -DHAS_PWRITE -DHAS_SYS_STATVFS_H -DINSTALL_PATH=\"/Users/rmcgibbo/local/cctools\" -g -D_REENTRANT -D_GNU_SOURCE -DBUILD_USER=\"rmcgibbo\" -DBUILD_HOST=\"Roberts-MacBook-Pro-2.local\" -DCCTOOLS_VERSION_MAJOR=3 -DCCTOOLS_VERSION_MINOR=4 -DCCTOOLS_VERSION_MICRO=2 -DCCTOOLS_OPSYS_DARWIN -DCCTOOLS_CPU_X86_64
CCTOOLS_INTERNAL_CCFLAGS= -I/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/dttools/src -I/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/sand/src -I/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/allpairs/src -I/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/wavefront/src -I/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/makeflow/src -I/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/ftp_lite/src -I/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/s3tools/src -I/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/chirp/src ${CCTOOLS_BASE_CCFLAGS}
CCTOOLS_CCFLAGS=-I${CCTOOLS_INSTALL_DIR}/include/cctools ${CCTOOLS_BASE_CCFLAGS}

CCTOOLS_CXX=@echo COMPILE $@; g++
CCTOOLS_BASE_CXXFLAGS=-D__EXTENSIONS__ -D_LARGEFILE64_SOURCE -D__LARGE64_FILES -Wall -Wno-unknown-pragmas -Wno-deprecated-declarations -fno-exceptions -fPIC -DHAS_LIBREADLINE -DHAS_STRSIGNAL -DHAS_PREAD -DHAS_PWRITE -DHAS_SYS_STATVFS_H -DINSTALL_PATH=\"/Users/rmcgibbo/local/cctools\" -g -D_REENTRANT -D_GNU_SOURCE -DBUILD_USER=\"rmcgibbo\" -DBUILD_HOST=\"Roberts-MacBook-Pro-2.local\" -DCCTOOLS_VERSION_MAJOR=3 -DCCTOOLS_VERSION_MINOR=4 -DCCTOOLS_VERSION_MICRO=2 -DCCTOOLS_OPSYS_DARWIN -DCCTOOLS_CPU_X86_64
CCTOOLS_INTERNAL_CXXFLAGS= -I/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/dttools/src -I/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/sand/src -I/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/allpairs/src -I/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/wavefront/src -I/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/makeflow/src -I/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/ftp_lite/src -I/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/s3tools/src -I/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/chirp/src ${CCTOOLS_BASE_CXXFLAGS}
CCTOOLS_CXXFLAGS=-I${CCTOOLS_INSTALL_DIR}/include/cctools ${CCTOOLS_BASE_CXXFLAGS}

CCTOOLS_LD=@echo LINK $@; gcc
CCTOOLS_BASE_LDFLAGS=-static-libgcc -lreadline -lncurses -ltermcap -lssl -lcrypto -lresolv -ldl -lstdc++ -lpthread -lz -lc -lm
CCTOOLS_INTERNAL_LDFLAGS=  -L/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/dttools/src -L/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/sand/src -L/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/allpairs/src -L/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/wavefront/src -L/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/makeflow/src -L/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/ftp_lite/src -L/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/s3tools/src -L/Users/rmcgibbo/local/monakos/modified-cctools-3.4.2/chirp/src ${CCTOOLS_BASE_LDFLAGS}
CCTOOLS_LDFLAGS=-L${CCTOOLS_INSTALL_DIR}/lib ${CCTOOLS_BASE_LDFLAGS}

CCTOOLS_MPI_LD=@echo MPI_LINK $@; 
CCTOOLS_USE_MPI=false

CCTOOLS_READLINE_LDFLAGS=

CCTOOLS_DYNAMIC_SUFFIX=dylib
CCTOOLS_DYNAMIC_FLAG=-dynamiclib
CCTOOLS_DYNAMIC_AUTH_LIBS=

CC=$(CCTOOLS_CC)
CCFLAGS=$(CCTOOLS_CCFLAGS)
LD=$(CCTOOLS_LD)
LDFLAGS=$(CCTOOLS_LDFLAGS)
CXX=$(CCTOOLS_CXX)
CXXFLAGS=$(CCTOOLS_CXXFLAGS)
MPILD=$(CCTOOLS_MPI_LD)

CCTOOLS_AR=ar

CCTOOLS_SWIG=/Library/Frameworks/EPD64.framework/Versions/Current/bin/swig

CCTOOLS_PERL=
CCTOOLS_PERL_CCFLAGS=
CCTOOLS_PERL_LDFLAGS=
CCTOOLS_PERL_VERSION=

CCTOOLS_PYTHON=/Library/Frameworks/EPD64.framework/Versions/Current//bin/python2
CCTOOLS_PYTHON_CCFLAGS=-I/Library/Frameworks/EPD64.framework/Versions/7.3/include/python2.7 -I/Library/Frameworks/EPD64.framework/Versions/7.3/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -DNDEBUG -g -O3 -arch x86_64
CCTOOLS_PYTHON_LDFLAGS=-L/Library/Frameworks/EPD64.framework/Versions/7.3/lib/python2.7/config -ldl -framework CoreFoundation EPD64.framework/Versions/7.3/Python -undefined dynamic_lookup
CCTOOLS_PYTHON_VERSION=2.7

CCTOOLS_WORK_QUEUE_BINDINGS= python

CCTOOLS_DOCTARGETS= htmlpages manpages

CCTOOLS_M4_ARGS=-DCCTOOLS_VERSION=3.4.2 -DCCTOOLS_RELEASE_DATE=02/10/2012

